name: General check-ups

on:
    push:
    branches: [ master ]

jobs:
    build-n-publish:
    name: Checking Python
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@master
        - name: Initialize Python 3.7
        uses: actions/setup-python@v1
        with:
            python-version: 3.7
        - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pandas
        - name: Pip install
        run: |
            echo "Build complete"
        - name: Build binary wheel and a source tarball
        run: python setup.py sdist
