name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
        echo "Done installing pip"
    - name: Install dependencies
      run: |
        pip install pandas numpy time os pandas_datareader csv json os ctypes
        echo "Done installing pandas"
    - name: Test code
      run: |
         python setup.py
